'use strict';
const $=id=>document.getElementById(id),NAMES=['LUCAS','QUENTIN','THEO'];
let registry=null,busy=false;
function read(k){try{return JSON.parse(localStorage.getItem(k)||'null')}catch{return null}}
function save(){localStorage.setItem('inst-v7-registry-pc',JSON.stringify(registry))}
function base(value){const u=new URL(value);if(u.protocol!=='https:'||!u.hostname.endsWith('.workers.dev')||u.username||u.password)throw Error('Utilisez l’adresse HTTPS workers.dev.');return u.origin}
function config(){const c={QUENTIN:'',LUCAS:'',THEO:''};for(const s of registry.stations)c[s.person]=registry.url+'/rss/rooms/'+s.id+'/'+s.token+'.xml';return c}
function phoneLink(){const u=new URL('telephone.html?v=10',location.href);u.hash=new URLSearchParams({relay:registry.url,stations:JSON.stringify(registry.stations.map(s=>({person:s.person,id:s.id,token:s.mobileToken})))});return u.href}
async function copy(text){try{await navigator.clipboard.writeText(text);$('status').textContent='Copié. Conservez ce contenu privé.'}catch{$('copyFallback').hidden=false;$('copyFallback').value=text;$('copyFallback').select();$('status').textContent='Copiez le contenu affiché ci-dessous.'}}
async function request(url,options){const r=await fetch(url,{...options,cache:'no-store',signal:AbortSignal.timeout(15000)}),d=await r.json();if(!r.ok)throw Error(d.error||'Relais indisponible');return d}
function render(){$('ready').hidden=!registry?.stations?.length;$('connect').disabled=busy;const list=$('profiles');list.replaceChildren();for(const s of registry?.stations||[]){const card=document.createElement('div'),label=document.createElement('strong'),note=document.createElement('p'),button=document.createElement('button');label.textContent=s.person;note.className='note';note.textContent='Profil permanent';button.className='danger';button.textContent='Révoquer ce prénom';button.disabled=busy;button.onclick=()=>revoke(s);card.append(label,note,button);list.append(card)}}
async function revoke(s){if(busy||!confirm('Révoquer '+s.person+' sur tous les téléphones ? Ses anciens liens privés cesseront de fonctionner.'))return;busy=true;render();try{await request(registry.url+'/rooms/'+s.id+'/close',{method:'POST',headers:{Authorization:'Bearer '+s.token,'Content-Type':'application/json'},body:'{}'});registry.stations=registry.stations.filter(x=>x.person!==s.person);save();$('status').textContent='Profil révoqué. Reconfigurez les accès, puis remplacez ProfilsScanner dans le flux et ouvrez le nouveau lien téléphone.'}catch(e){$('status').textContent=e.message}finally{busy=false;render()}}
$('connect').onclick=async()=>{if(busy)return;busy=true;render();try{const url=base($('url').value.trim()),key=$('access').value;if(key.length<32)throw Error('Saisissez votre ACCESS_KEY actuel, 32 caractères minimum.');const health=await request(url+'/health');if(health.version<10||health.bridge!=='rss')throw Error('Mettez le Worker à jour en V10 avec METTRE_A_JOUR_SANS_CHANGER_CLE.bat.');const stations=[];for(const person of NAMES){const r=await request(url+'/rooms',{method:'POST',headers:{'Content-Type':'application/json','X-Access-Key':key},body:JSON.stringify({person})});stations.push({person:r.person,id:r.id,token:r.pcToken,mobileToken:r.mobileToken})}registry={role:'pc',url,stations};save();$('access').value='';$('status').textContent='Profils prêts. Copiez ProfilsScanner pour le flux, puis gardez le lien téléphone en favori.'}catch(e){$('status').textContent=e.message}finally{busy=false;render()}};
$('phoneLink').onclick=()=>copy(phoneLink());$('copyConfig').onclick=()=>copy(JSON.stringify(config(),null,2));
try{const r=read('inst-v7-registry-pc');if(r&&Array.isArray(r.stations)&&r.stations.every(s=>NAMES.includes(s.person)&&/^[a-f0-9]{64}$/.test(s.token)&&/^[a-f0-9]{64}$/.test(s.mobileToken))){registry=r;registry.url=base(r.url);$('url').value=registry.url;$('status').textContent='Vos profils existants sont conservés. Mettez le Worker V10 à jour avant de configurer le flux.'}else $('status').textContent='Configurer le relais avec votre code privé existant.'}catch(e){$('status').textContent=e.message}render();
