'use strict';
const $=id=>document.getElementById(id),NAMES=['LUCAS','QUENTIN','THEO'];
let registry=null,session=null,person='QUENTIN',task=null,result=null,batch={items:[],mallette:''},pending=null,taskMeta=null,handoff=null,submitted=false,nonce='',busy=false,loading=false;
const status=s=>$('status').textContent=s;
const valid=s=>typeof s==='string'&&s.length>0&&s.length<=255&&!/[|\r\n\0]/.test(s);
function base(value){const u=new URL(value);if(u.protocol!=='https:'||!u.hostname.endsWith('.workers.dev')||u.username||u.password)throw Error('Utilisez l’adresse HTTPS workers.dev du relais.');return u.origin}
function store(key,value){try{localStorage.setItem(key,JSON.stringify(value));return true}catch{status('Stockage indisponible : gardez la page ouverte et conservez votre lien privé.');return false}}
function read(key){try{return JSON.parse(localStorage.getItem(key)||'null')}catch{return null}}
function validateRegistry(r){if(!r||!['pc','mobile'].includes(r.role)||!Array.isArray(r.stations)||r.stations.length>3)throw Error('Lien téléphone invalide.');r.url=base(r.url);const names=new Set();for(const s of r.stations){if(!NAMES.includes(s.person)||names.has(s.person)||!/^[-a-f0-9]{36}$/.test(s.id)||! /^[a-f0-9]{64}$/.test(s.token)||(r.role==='pc'&&!/^[a-f0-9]{64}$/.test(s.mobileToken)))throw Error('Profil invalide.');names.add(s.person)}return r}
function stateKey(){return 'inst-v7-state-'+registry.role+'-'+person}
function save(){if(!registry)return;store('inst-v7-registry-'+registry.role,registry);store('inst-v7-last-role',registry.role);store('inst-v7-person-'+registry.role,person);if(session)store(stateKey(),{id:session.id,token:session.token,task,result,batch,pending,taskMeta,submitted,handoff:registry.role==='pc'&&handoff?.person===person?handoff:null})}
function selectPerson(next){if(busy||loading||!$('scanner').hidden)return;save();person=next;session=null;task=null;result=null;batch={items:[],mallette:''};pending=null;taskMeta=null;submitted=false;const station=registry?.stations.find(s=>s.person===person);if(station){session={...station,url:registry.url,role:registry.role};const cached=read(stateKey());if(cached?.id===session.id&&cached.token===session.token){task=cached.task;result=cached.result;batch=cached.batch||batch;pending=cached.pending;taskMeta=cached.taskMeta;submitted=!!cached.submitted;if(!handoff&&cached.handoff)handoff=cached.handoff}}if(handoff&&person===handoff.person)$('cm').value=handoff.cm;else $('cm').value=task?.cm||'';save();render();status(session?'En attente d’une demande pour '+person:'Configurez ou renouvelez le profil '+person+'.');poll()}
async function call(url,options){const r=await fetch(url,{...options,cache:'no-store',signal:AbortSignal.timeout(15000)});const data=await r.json();if(!r.ok){const e=Error(data.error||'Erreur du relais');e.status=r.status;throw e}return data}
async function api(path,body){if(!session)throw Error('Profil non connecté.');return call(session.url+'/rooms/'+session.id+'/'+path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+session.token,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})})}
function phoneLink(){const u=new URL('telephone.html?v=8',location.href);u.hash=new URLSearchParams({relay:registry.url,stations:JSON.stringify(registry.stations.map(s=>({person:s.person,id:s.id,token:registry.role==='pc'?s.mobileToken:s.token})))});return u.href}
function listInto(id,items){const list=$(id);list.replaceChildren();for(const code of items){const row=document.createElement('div');row.className='item';const icon=document.createElement('span');icon.textContent='✓';const strong=document.createElement('strong');strong.textContent=code;row.append(icon,strong);list.append(row)}}
function render(){const mobile=registry?.role==='mobile';$('setup').hidden=!!session||mobile;$('pc').hidden=!session||mobile;$('task').hidden=!session||!mobile||!task;$('output').hidden=!session||mobile||!result;$('link').hidden=!registry||registry.stations.length===0;$('disconnect').hidden=!registry;$('revoke').hidden=!session||mobile;$('identity').textContent=session?person+' · '+(mobile?'Téléphone':'PC')+' · liaison permanente':'';$('profiles').querySelector('h2').textContent=mobile?'Qui utilise ce téléphone ?':'Destinataire du scan';document.querySelectorAll('[data-name]').forEach(b=>{b.classList.toggle('active',b.dataset.name===person);b.disabled=busy||loading||!$('scanner').hidden});$('connect').disabled=busy;$('send').disabled=busy||loading||!!task||!!result;$('finish').disabled=busy||loading||submitted;$('scan').disabled=busy||submitted;$('case').disabled=busy||submitted;if(task)$('taskTitle').textContent='Véhicule '+task.cm;$('batch').textContent=batch.items.length+' matériel(s) · Mallette : '+(batch.mallette||'aucune');listInto('mobileItems',batch.items);$('cm').readOnly=!!handoff&&handoff.person===person;$('contextNote').textContent=handoff?'Fiche n° '+handoff.planning+' · destinée à '+handoff.person:'Ouvrez la liaison depuis le global pour recevoir sa référence de fiche.';if(result){listInto('pcItems',result.items);$('resultCase').textContent='Véhicule '+result.cm+' · '+result.person+' · Mallette : '+(result.mallette||'aucune');try{$('import').href=RetourCore.importURL($('appLink').value,result,taskMeta);$('import').setAttribute('aria-disabled','false');$('importNote').textContent='Ouvrez le lot et confirmez dans Power Apps.'}catch(e){$('import').href='#';$('import').setAttribute('aria-disabled','true');$('importNote').textContent=e.message}}}
$('names').onclick=e=>{const name=e.target.dataset.name;if(NAMES.includes(name))selectPerson(name)};
$('connect').onclick=async()=>{if(busy||loading)return;busy=true;render();try{const url=base($('url').value.trim()),key=$('access').value;if(key.length<32)throw Error('Renseignez votre ACCESS_KEY (32 caractères minimum).');const stations=[];for(const name of NAMES){const r=await call(url+'/rooms',{method:'POST',headers:{'Content-Type':'application/json','X-Access-Key':key},body:JSON.stringify({person:name})});if(r.permanent!==true)throw Error('Mettez d’abord le relais Cloudflare à jour avec le Worker V7.');stations.push({person:r.person,id:r.id,token:r.pcToken,mobileToken:r.mobileToken})}registry=validateRegistry({role:'pc',url,stations});$('access').value='';status('Trois profils configurés. Copiez le lien permanent sur les téléphones.')}catch(e){status(e.message)}finally{busy=false;if(registry)selectPerson(person);else render()}};
$('link').onclick=async()=>{try{const link=phoneLink();try{await navigator.clipboard.writeText(link);status('Lien permanent copié. Gardez-le en favori privé sur le téléphone.')}catch{$('linkText').hidden=false;$('linkText').value=link;status('Copiez le lien permanent affiché.')}}catch(e){status(e.message)}};
$('send').onclick=async()=>{if(busy||loading||!session||task||result)return;busy=true;render();try{if(!handoff||handoff.person!==person)throw Error('Ouvrez cette fiche depuis le global et sélectionnez son destinataire : '+(handoff?.person||'non renseigné'));const cm=$('cm').value.trim().toUpperCase();if(cm!==handoff.cm)throw Error('Contre-marque différente du brouillon.');pending=pending||{id:crypto.randomUUID(),cm};taskMeta={...handoff,id:pending.id};save();const r=await api('task',pending);task=r.task;pending=null;save();status('Demande envoyée à '+person+'.')}catch(e){if([400,409].includes(e.status))pending=null;save();status(e.message)}finally{busy=false;render()}};
async function poll(){if(!session||loading||busy||document.hidden)return;loading=true;const identity=session.token;try{const r=await api('status');if(identity!==session?.token)return;if(session.role==='pc'){task=r.task;result=r.result;if(result){pending=null;status('Lot reçu. Importez puis confirmez dans Power Apps.')}else status(task?(r.mobileOnline?'Téléphone connecté · demande en cours.':'Demande conservée · sélectionnez '+person+' sur le téléphone.'):(r.mobileOnline?'Téléphone prêt pour '+person+'.':'En attente du téléphone sélectionné sur '+person+'.'))}else{if(r.task&&r.task.id!==task?.id){task=r.task;batch={items:[],mallette:''};submitted=false}if(!r.task){task=null;batch={items:[],mallette:''}}submitted=!!r.received;status(!task?'En attente d’une demande pour '+person:submitted?'Lot transmis. En attente de confirmation sur le PC.':'Demande reçue pour '+task.cm+'. Vous pouvez scanner.')}save()}catch(e){if([403,410].includes(e.status))status('Ce lien pour '+person+' a été révoqué ou remplacé. Les scans locaux restent conservés. Demandez un nouveau lien au PC.');else status(e.message+' · Scans locaux conservés.')}finally{loading=false;render()}}
function scan(mode){if(!task||busy||submitted)return;nonce=crypto.randomUUID();const u=new URL('scan-mobile.html',location.href);u.search=new URLSearchParams({mode,cm:task.cm,items:batch.items.join('|'),mallette:batch.mallette,nonce,scanSessionId:task.id,scanRequest:task.id});$('scanner').src=u.href;$('scanner').hidden=false;render()}
$('scan').onclick=()=>scan('materiel');$('case').onclick=()=>scan('mallette');
window.addEventListener('message',e=>{const d=e.data;if(e.origin!==location.origin||e.source!==$('scanner').contentWindow||!task||!d||d.type!=='instrumentation-mobile-batch'||d.nonce!==nonce||d.request!==task.id||d.cm!==task.cm)return;if(!Array.isArray(d.items)||d.items.length>200||!d.items.every(valid)||typeof d.mallette!=='string'||d.mallette.length>255||/[|\r\n\0]/.test(d.mallette)){status('Lot invalide.');return}batch={items:[...new Set(d.items)],mallette:d.mallette};$('scanner').hidden=true;$('scanner').src='about:blank';save();render()});
$('finish').onclick=async()=>{if(!task||busy||loading||submitted)return;busy=true;render();try{if(!batch.items.length)throw Error('Scannez au moins un matériel.');await api('result',{id:task.id,cm:task.cm,...batch});submitted=true;save();status('Lot conservé dans le relais pour confirmation PC.')}catch(e){status(e.message+' · Le lot local est conservé.')}finally{busy=false;render()}};
$('import').onclick=e=>{if($('import').getAttribute('aria-disabled')==='true')e.preventDefault()};
$('copy').onclick=async()=>{try{await navigator.clipboard.writeText(JSON.stringify({...result,planning:taskMeta?.planning,jeton:taskMeta?.jeton}));status('Lot copié. Collez-le dans la fiche Power Apps restée ouverte, puis cliquez sur Charger le lot.')}catch{status('Copie impossible dans ce navigateur. Conservez cette page.')}};
$('ack').onclick=async()=>{if(!result||busy||loading)return;if(!confirm('Le montage est-il confirmé ou annulé dans Power Apps ? Ce bouton efface le lot du relais.'))return;busy=true;try{await api('ack',{id:result.id});result=null;task=null;pending=null;taskMeta=null;handoff=null;$('cm').value='';save();status('Prêt pour le véhicule suivant. Le lien téléphone reste valide.')}catch(e){status(e.message)}finally{busy=false;render()}};
$('disconnect').onclick=()=>{if(busy||loading)return;if(!confirm('Déconnecter cet appareil ? Les liens restent valides. Conservez les lots avant de continuer.'))return;save();registry=null;session=null;task=null;result=null;batch={items:[],mallette:''};$('linkText').hidden=true;render();status('Appareil déconnecté. Votre lien permanent reste utilisable.')};
$('revoke').onclick=async()=>{if(!session||session.role!=='pc'||busy||loading)return;if(!confirm('Révoquer '+person+' pour tous les téléphones ? Les anciennes clés de ce prénom cesseront de fonctionner, et son lot du relais sera supprimé. SharePoint reste inchangé.'))return;busy=true;try{await api('close',{});registry.stations=registry.stations.filter(s=>s.person!==person);try{localStorage.removeItem(stateKey())}catch{};store('inst-v7-registry-pc',registry);session=null;task=null;result=null;pending=null;taskMeta=null;batch={items:[],mallette:''};status('Profil '+person+' révoqué. Reconfigurez les trois prénoms avec ACCESS_KEY pour générer le nouveau lien.')}catch(e){status(e.message)}finally{busy=false;render()}};
try{const p=new URLSearchParams(location.hash.slice(1));if(p.has('stations')){registry=validateRegistry({role:'mobile',url:p.get('relay'),stations:JSON.parse(p.get('stations'))});person=read('inst-v7-person-mobile')||'QUENTIN'}else{if(p.has('planning')){handoff={cm:p.get('cm'),planning:p.get('planning'),jeton:p.get('jeton'),person:p.get('person')};if(!NAMES.includes(handoff.person))throw Error('Destinataire invalide.');person=handoff.person;registry=read('inst-v7-registry-pc');history.replaceState(null,'',location.pathname+location.search)}else{const role=location.pathname.endsWith('/telephone.html')?'mobile':location.pathname.endsWith('/acces-scanner.html')?'pc':read('inst-v7-last-role')||'pc';registry=read('inst-v7-registry-'+role);person=read('inst-v7-person-'+role)||'QUENTIN'}if(registry)validateRegistry(registry)}$('appLink').value=read('inst-v7-app-link')||localStorage.getItem('instrumentation-global-link')||''}catch(e){registry=null;status(e.message)}
$('appLink').oninput=()=>{try{RetourCore.appURL($('appLink').value);store('inst-v7-app-link',$('appLink').value)}catch{};render()};
selectPerson(NAMES.includes(person)?person:'QUENTIN');setInterval(poll,5000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)poll()});

if(location.pathname.endsWith('/acces-scanner.html')){document.body.classList.add('admin-page');document.querySelector('h1').textContent='Accès scanner';document.querySelector('header p').textContent='Configurer les téléphones, copier leur lien privé et révoquer un prénom.';}
if(location.pathname.endsWith('/telephone.html')){document.body.classList.add('phone-page');document.querySelector('h1').textContent='Votre atelier, en poche.';document.querySelector('header p').textContent='Choisissez votre prénom. Recevez une fiche, scannez et envoyez le lot au PC.';}
