'use strict';
const $=id=>document.getElementById(id);let handoff=null,taskMeta=null,submitted=false;try{const h=new URLSearchParams(location.hash.slice(1));if(!h.has('token')&&h.has('planning')){handoff={cm:h.get('cm'),planning:h.get('planning'),jeton:h.get('jeton'),person:h.get('person')};history.replaceState(null,'',location.pathname+location.search)}}catch{};let person=handoff?.person||'QUENTIN',session=null,task=null,batch={items:[],mallette:''},nonce='',busy=false,loading=false,pending=null,result=null;
const status=s=>$('status').textContent=s;
const valid=s=>typeof s==='string'&&s.length>0&&s.length<=255&&!/[|\r\n\0]/.test(s);
function base(s){const u=new URL(s);if(u.protocol!=='https:'||!u.hostname.endsWith('.workers.dev')||u.username||u.password)throw Error('Utilise l’adresse HTTPS …workers.dev de ton relais.');return u.origin}
function save(){try{sessionStorage.setItem('inst-relay-v3',JSON.stringify({session,task,batch,pending,result,taskMeta}))}catch{status('Stockage local indisponible : conserve cette page ouverte.')}}
function renderBase(){const mobile=session?.role==='mobile';$('setup').hidden=!!session;$('pc').hidden=!session||mobile;$('task').hidden=!mobile||!task;$('link').hidden=!session||mobile;$('disconnect').hidden=!session;$('identity').textContent=session?'Prénom : '+session.person+' · '+(mobile?'Téléphone':'PC')+' · Retour PC V6':'';$('send').disabled=busy||!!task;$('finish').disabled=busy;$('scan').disabled=busy;$('case').disabled=busy;if(task)$('taskTitle').textContent='Véhicule '+task.cm;$('batch').textContent=batch.items.length+' matériel(s) · Mallette : '+(batch.mallette||'aucune');$('output').hidden=!result;if(result)$('result').textContent=JSON.stringify(result,null,2)}
async function api(path,body){if(!session)throw Error('Liaison absente');return call(session.url+'/rooms/'+session.id+'/'+path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+session.token,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})})}
async function call(url,opts){const r=await fetch(url,{...opts,cache:'no-store',signal:AbortSignal.timeout(15000)});const b=await r.json();if(!r.ok){const e=Error(b.error||'Erreur du relais');e.status=r.status;throw e}return b}
$('names').onclick=e=>{if(!e.target.dataset.name||busy)return;person=e.target.dataset.name;document.querySelectorAll('[data-name]').forEach(x=>x.classList.toggle('active',x.dataset.name===person))};
$('connect').onclick=async()=>{if(busy)return;busy=true;$('connect').disabled=true;try{const url=base($('url').value.trim());const key=$('access').value;if(key.length<32)throw Error('Le code ACCESS_KEY doit contenir au moins 32 caractères.');const r=await call(url+'/rooms',{method:'POST',headers:{'Content-Type':'application/json','X-Access-Key':key},body:JSON.stringify({person})});session={url,id:r.id,token:r.pcToken,mobileToken:r.mobileToken,person:r.person,role:'pc',expires:r.expires};$('access').value='';save();status('Liaison créée. Ouvre le lien privé sur le téléphone.');render();await poll()}catch(e){status(e.message)}finally{busy=false;$('connect').disabled=false;render()}};
function phoneLink(){const u=new URL(location.href);u.hash=new URLSearchParams({relay:session.url,id:session.id,token:session.mobileToken,person:session.person});return u.href}
$('link').onclick=async()=>{const link=phoneLink();try{await navigator.clipboard.writeText(link);status('Lien privé copié : ouvre-le sur le téléphone.')}catch{$('linkText').hidden=false;$('linkText').value=link;status('Sélectionne et copie le lien privé affiché.')}};
$('send').onclick=async()=>{if(busy||task)return;busy=true;render();try{const cm=$('cm').value.trim().toUpperCase();if(handoff&&handoff.person!==session.person)throw Error('Cette fiche est destinée à '+handoff.person+'. Créez la liaison avec ce prénom.');if(result)throw Error('Conservez et confirmez le lot reçu avant de continuer.');if(!cm)throw Error('Renseigne la contre-marque.');if(pending&&pending.cm!==cm)throw Error('Réessaie la demande en attente avec la même contre-marque.');pending=pending||{id:crypto.randomUUID(),cm};if(handoff){if(cm!==handoff.cm)throw Error("La contre-marque diffère du brouillon Power Apps.");taskMeta={...handoff,id:pending.id};}save();const r=await api('task',pending);task=r.task;pending=null;save();status('Demande enregistrée dans le relais. En attente du téléphone.')}catch(e){if(e.status===400||e.status===409){pending=null;save()}status(e.message+' Tu peux réessayer sans fermer cette page.')}finally{busy=false;render()}};
async function poll(){if(!session||loading||busy||document.hidden)return;loading=true;try{if(session.expires<Date.now())throw Error('Liaison expirée. Ferme-la et crée-en une nouvelle.');const r=await api('status');if(session.role==='pc'){
 if(r.task)task=r.task;else if(!r.result)task=null;
 if(r.result){result=r.result;pending=null;status('Scans reçus sur le PC. Ils ne sont pas encore enregistrés dans SharePoint.')}else if(task)status(r.mobileOnline?'Téléphone connecté. Demande en cours pour '+task.cm:'Demande conservée. Téléphone absent ou page en arrière-plan.');else status(r.mobileOnline?'Téléphone connecté : prêt à recevoir.':'Liaison prête. En attente du téléphone.');
 }else{
 if(r.task&&r.task.id!==task?.id){task=r.task;batch={items:[],mallette:''};submitted=false}
 submitted=!!r.received;if(!r.task){task=null;batch={items:[],mallette:''};status('En attente d’une demande pour '+session.person)}else if(r.received)status('Résultat conservé par le relais. En attente du PC.');else status('Demande reçue pour '+task.cm+'. Tu peux scanner.');
 }save();render()}catch(e){status(e.message+' Les scans locaux sont conservés.')}finally{loading=false}}
function scan(mode){if(!task||busy)return;nonce=crypto.randomUUID();const u=new URL('scan-mobile.html',location.href);u.search=new URLSearchParams({mode,cm:task.cm,items:batch.items.join('|'),mallette:batch.mallette,nonce,scanSessionId:nonce,scanRequest:task.id});$('scanner').src=u.href;$('scanner').hidden=false}
$('scan').onclick=()=>scan('materiel');$('case').onclick=()=>scan('mallette');
window.addEventListener('message',e=>{const d=e.data;if(e.origin!==location.origin||e.source!==$('scanner').contentWindow||!task||!d||d.type!=='instrumentation-mobile-batch'||d.nonce!==nonce||d.request!==task.id||d.cm!==task.cm)return;if(!Array.isArray(d.items)||d.items.length>200||!d.items.every(valid)||typeof d.mallette!=='string'||d.mallette.length>255||/[|\r\n\0]/.test(d.mallette)){status('Lot invalide : maximum 200 matériels.');return}batch={items:[...new Set(d.items)],mallette:d.mallette};$('scanner').hidden=true;$('scanner').src='about:blank';save();render()});
$('finish').onclick=async()=>{if(!task||busy||submitted)return;busy=true;render();try{if(!batch.items.length)throw Error('Scanne au moins un matériel.');await api('result',{id:task.id,cm:task.cm,...batch});submitted=true;save();status('Résultat conservé dans le relais. Le PC le récupérera automatiquement.')}catch(e){status(e.message+' Le lot est conservé ; réessaie.')}finally{busy=false;render()}};
$('copy').onclick=async()=>{try{await navigator.clipboard.writeText(JSON.stringify(result));status('Résultat copié. Aucun enregistrement SharePoint effectué.')}catch{status('Sélectionne le résultat affiché pour le copier.')}};
$('ack').onclick=async()=>{if(!result||busy)return;if(!confirm('As-tu conservé le résultat ? Cela libère la liaison pour le véhicule suivant et efface le résultat du relais.'))return;busy=true;try{await api('ack',{id:result.id});result=null;task=null;pending=null;taskMeta=null;handoff=null;$('cm').value='';save();status('Prêt pour le véhicule suivant.')}catch(e){status(e.message)}finally{busy=false;render()}};
$('disconnect').onclick=async()=>{if(busy)return;if(!confirm('Fermer cette liaison ? Conserve les résultats avant de continuer.'))return;busy=true;try{if(session.role==='pc')await api('close',{});session=null;task=null;result=null;pending=null;batch={items:[],mallette:''};sessionStorage.removeItem('inst-relay-v3');$('linkText').hidden=true;status('Liaison fermée.')}catch(e){if(e.status===410){session=null;task=null;result=null;pending=null;sessionStorage.removeItem('inst-relay-v3');status('Session expirée supprimée.')}else status(e.message)}finally{busy=false;render()}};
try{const p=new URLSearchParams(location.hash.slice(1));if(p.has('token')){if(!/^[a-f0-9]{64}$/.test(p.get('token'))||!/^[-a-f0-9]{36}$/.test(p.get('id'))||!['LUCAS','QUENTIN','THEO'].includes(p.get('person')))throw Error('Lien téléphone invalide');session={url:base(p.get('relay')),id:p.get('id'),token:p.get('token'),person:p.get('person'),role:'mobile',expires:Date.now()+86400000};save();history.replaceState(null,'',location.pathname+location.search)}else{const s=JSON.parse(sessionStorage.getItem('inst-relay-v3')||'null');if(s?.session){session=s.session;task=s.task;batch=s.batch||batch;pending=s.pending;result=s.result;taskMeta=s.taskMeta||null;base(session.url)}}}catch(e){session=null;status(e.message)}if(handoff){$('cm').value=handoff.cm||'';person=handoff.person;document.querySelectorAll('[data-name]').forEach(x=>x.classList.toggle('active',x.dataset.name===person))}try{$('appLink').value=localStorage.getItem('instrumentation-global-link')||''}catch{};$('appLink').oninput=()=>{try{RetourCore.appURL($('appLink').value);localStorage.setItem('instrumentation-global-link',$('appLink').value)}catch{};render()};render();poll();setInterval(poll,5000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)poll()});

function listInto(id,items){const list=$(id);list.replaceChildren();for(const code of items){const row=document.createElement('div');row.className='item';const icon=document.createElement('span');icon.textContent='✓';const text=document.createElement('strong');text.textContent=code;row.append(icon,text);list.append(row)}}
function render(){renderBase();const mobile=session?.role==='mobile';$('contextNote').textContent=handoff?'Brouillon Power Apps n° '+handoff.planning+' · destinataire '+handoff.person:'Ouvrez cette page depuis le bouton « Ouvrir la liaison PC » du global pour lier le lot à sa fiche.';$('cm').readOnly=!!handoff;$('scan').disabled=busy||submitted;$('case').disabled=busy||submitted;$('finish').disabled=busy||submitted;listInto('mobileItems',batch.items);if(result){listInto('pcItems',result.items);$('resultCase').textContent='Véhicule '+result.cm+' · '+result.person+' · Mallette : '+(result.mallette||'aucune');try{$('import').href=RetourCore.importURL($('appLink').value,result,taskMeta);$('import').setAttribute('aria-disabled','false');$('importNote').textContent='Le global s’ouvre avec le lot à vérifier. La fiche véhicule est déjà sauvegardée.'}catch(e){$('import').href='#';$('import').setAttribute('aria-disabled','true');$('importNote').textContent=e.message}}}
$('import').onclick=e=>{if($('import').getAttribute('aria-disabled')==='true'){e.preventDefault();return}status('Lot ouvert pour contrôle dans Power Apps. Confirmez là-bas avant de libérer cette liaison.');};
