'use strict';
const $=id=>document.getElementById(id),NAMES=['LUCAS','QUENTIN','THEO'];
const valid=s=>typeof s==='string'&&s.trim().length>0&&s.length<=255&&!/[|\r\n\0]/.test(s)&&!s.includes('[object Object]');
let registry=null,session=null,person='QUENTIN',task=null,batch={items:[],mallette:''},seq=0,submitted=false,stagedRevision=0,revision=0,nonce='',polling=false,sending=false,finishing=false,queued=null,progressTimer=null;
function read(k){try{return JSON.parse(localStorage.getItem(k)||'null')}catch{return null}}
function store(k,v){try{localStorage.setItem(k,JSON.stringify(v));return true}catch{$('status').textContent='Stockage local indisponible : gardez cette page ouverte.';return false}}
let device=read('inst-v10-device');if(!device){device=crypto.randomUUID();store('inst-v10-device',device)}
const key=()=> 'inst-v10-phone-'+person;
function save(){if(!registry||!session)return;store(key(),{station:session.id,token:session.token,task,batch,seq,submitted,revision,stagedRevision});store('inst-v7-registry-mobile',registry);store('inst-v7-person-mobile',person)}
function validateRegistry(r){if(!r||!Array.isArray(r.stations)||!r.stations.length)throw Error('Téléphone non raccordé. Ouvrez son lien privé une fois depuis Accès scanner.');const u=new URL(r.url);if(u.protocol!=='https:'||!u.hostname.endsWith('.workers.dev'))throw Error('Relais invalide.');r.url=u.origin;r.role='mobile';const names=new Set();for(const s of r.stations){if(!NAMES.includes(s.person)||names.has(s.person)||!/^[-a-f0-9]{36}$/.test(s.id)||!/^[a-f0-9]{64}$/.test(s.token))throw Error('Lien téléphone invalide.');names.add(s.person)}return r}
async function api(path,body,captured=session){if(!captured)throw Error('Téléphone non raccordé.');const r=await fetch(captured.url+'/rooms/'+captured.id+'/'+path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+captured.token,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{}),cache:'no-store',signal:AbortSignal.timeout(15000)});const d=await r.json();if(!r.ok){const e=Error(d.error||'Relais indisponible');e.status=r.status;throw e}return d}
function render(){const blocked=finishing||sending||polling||!$('scanner').hidden;document.querySelectorAll('[data-person]').forEach(b=>{b.classList.toggle('active',b.dataset.person===person);b.disabled=blocked});$('identity').textContent=session?person+' · téléphone raccordé jusqu’à révocation':'Ouvrez le lien privé de ce téléphone.';$('task').hidden=!task;$('vehicle').textContent='Véhicule '+(task?.cm||'');$('count').textContent=batch.items.length+' matériel(s)';$('caseNumber').textContent='Mallette : '+(batch.mallette||'—');$('scan').disabled=finishing||submitted||!!task?.feedback;$('case').disabled=$('scan').disabled;$('finish').disabled=finishing||sending||!batch.items.length||!!task?.feedback;$('finish').textContent=finishing?'Enregistrement…':submitted?'Réessayer l’envoi du même lot':'✓  Terminer le scan';const list=$('items');list.replaceChildren();for(const code of batch.items){const row=document.createElement('div');row.className='item';const check=document.createElement('span');check.className='check';check.textContent='✓';const label=document.createElement('strong');label.textContent=code;row.append(check,label);if(!submitted){const remove=document.createElement('button');remove.textContent='×';remove.setAttribute('aria-label','Retirer '+code);remove.onclick=()=>{batch.items=batch.items.filter(x=>x!==code);save();render();queueProgress()};row.append(remove)}list.append(row)}$('delivery').textContent=submitted?(stagedRevision>=revision&&revision>0?'Lot reçu dans SharePoint. Le PC peut confirmer le montage.':'Lot validé dans le relais. En attente du transfert vers SharePoint…'):'Liste synchronisée progressivement avec le PC après le démarrage du flux.'}
function archive(){if(!task)return;const history=read('inst-v10-history-'+person)||[];store('inst-v10-history-'+person,[{task,batch,submitted,at:Date.now()},...history.filter(x=>x.task.id!==task.id)].slice(0,20))}
function select(next){if(finishing||sending||polling||!$('scanner').hidden)return;save();person=next;session=registry?.stations.find(s=>s.person===person);if(session)session={...session,url:registry.url};task=null;batch={items:[],mallette:''};submitted=false;seq=0;revision=0;stagedRevision=0;queued=null;const cached=read(key());if(session&&cached?.station===session.id&&cached.token===session.token){task=cached.task;batch=cached.batch||batch;submitted=!!cached.submitted;seq=cached.seq||0;revision=cached.revision||0;stagedRevision=cached.stagedRevision||0}else if(session){const old=read('inst-v7-state-mobile-'+person);if(old?.id===session.id&&old.token===session.token&&old.task){task=old.task;batch=old.batch||batch}}save();render();$('status').textContent=session?'En attente d’une demande pour '+person:'Ouvrez le lien privé de ce téléphone.';poll()}
async function poll(){if(!session||polling||finishing||document.hidden)return;polling=true;const captured=session;try{const d=await api('status',null,captured);if(captured.token!==session?.token)return;if(d.task&&d.task.id!==task?.id){if(!$('scanner').hidden){$('scanner').hidden=true;$('scanner').src='about:blank'}archive();task=d.task;batch={items:[],mallette:''};seq=0;submitted=false;revision=0;stagedRevision=0;queued=null;PhoneAlerts.arrival(person,task.id)}else if(d.task){task=d.task}if(!d.task){if(!$('scanner').hidden){$('scanner').hidden=true;$('scanner').src='about:blank'}if(task)archive();task=null;batch={items:[],mallette:''};submitted=false;queued=null;PhoneAlerts.forget(person)}if(task){task.feedback=!!d.feedback;submitted=submitted||!!d.received;stagedRevision=Math.max(stagedRevision,d.stagedRevision||0);revision=Math.max(revision,d.revision||0)} $('feedback').hidden=!d.feedback;$('feedbackText').textContent=d.feedback?.message||'';$('status').textContent=!task?(d.lastCompletion?.status==='Terminé'?'Montage confirmé sur le PC. En attente pour '+person+'.':'En attente d’une demande pour '+person):d.feedback?'Anomalie à corriger : attendez une nouvelle demande.':submitted?(stagedRevision>=revision&&revision>0?'Lot reçu sur le PC. Confirmation du montage en attente.':'Lot enregistré dans Cloudflare. Le flux prépare le retour SharePoint…'):'Demande reçue pour '+task.cm+'. Vous pouvez scanner.';save();if(task&&!submitted&&!queued&&!sending&&seq>(d.clientSeq??-1)&&batch.items.length)queueProgress()}catch(e){$('status').textContent=e.status===403||e.status===410?'Accès révoqué. Demandez le nouveau lien privé. Scans locaux conservés.':e.message+' · Scans locaux conservés.'}finally{polling=false;render()}}
function payload(){return {id:task.id,cm:task.cm,items:[...batch.items],mallette:batch.mallette,device,seq:++seq}}
function queueProgress(){if(!task||submitted||finishing)return;queued=payload();save();if(progressTimer)clearTimeout(progressTimer);progressTimer=setTimeout(flushProgress,350)}
async function flushProgress(){if(sending||finishing||!queued||!task)return;sending=true;const body=queued,captured=session;queued=null;try{const d=await api('progress',body,captured);if(captured.token===session?.token&&task?.id===body.id){revision=Math.max(revision,d.revision||0);save()}}catch(e){if(captured.token===session?.token&&task?.id===body.id){if(!queued&&![400,403,409,410].includes(e.status))queued=body;$('status').textContent=e.message+' · Liste conservée. Réessai au prochain rafraîchissement.'}}finally{sending=false;render();if(queued&&!finishing)progressTimer=setTimeout(flushProgress,1500)}}
async function finish(){if(!task||finishing||sending)return;if(!batch.items.length){$('status').textContent='Scannez au moins un matériel.';return}finishing=true;queued=null;if(progressTimer)clearTimeout(progressTimer);render();try{const body=payload();save();const d=await api('result',body);submitted=true;revision=Math.max(revision,d.revision||0);save();$('status').textContent='Scan terminé. Lot enregistré dans Cloudflare, transfert SharePoint en cours.'}catch(e){$('status').textContent=e.message+' · Lot conservé : vous pouvez réessayer.'}finally{finishing=false;render();poll()}}
async function scan(mode){if(!task||submitted||finishing)return;queueProgress();nonce=crypto.randomUUID();const u=new URL('scan-mobile.html?v=10',location.href);const cached=store('instrumentation-batch-'+task.id+'-'+task.cm,{items:[...batch.items],mallette:batch.mallette,cm:task.cm,at:Date.now()});for(const [k,v] of Object.entries({mode,cm:task.cm,items:cached?'':batch.items.join('|'),mallette:cached?'':batch.mallette,nonce,scanSessionId:task.id,scanRequest:task.id}))u.searchParams.set(k,v);$('scanner').src=u.href;$('scanner').hidden=false;render()}
window.addEventListener('message',async e=>{const d=e.data;if(e.origin!==location.origin||e.source!==$('scanner').contentWindow||!task||!d||d.nonce!==nonce||d.request!==task.id||d.cm!==task.cm)return;if(!['instrumentation-mobile-batch','instrumentation-mobile-progress','instrumentation-mobile-abandon'].includes(d.type))return;if(!Array.isArray(d.items)||d.items.length>200||!d.items.every(valid)||typeof d.mallette!=='string'||d.mallette.length>255||/[|\r\n\0]/.test(d.mallette)){ $('status').textContent='Lot invalide : un code reçu n’est pas du texte. Les scans précédents sont conservés.';return}batch={items:[...new Set(d.items)],mallette:d.mallette};save();if(d.type==='instrumentation-mobile-batch'){$('scanner').hidden=true;$('scanner').src='about:blank';if(sending){queued=null;$('status').textContent='Dernier scan en transmission. Patientez…';while(sending)await new Promise(r=>setTimeout(r,80))}finish()}else{if(d.type==='instrumentation-mobile-abandon'){$('scanner').hidden=true;$('scanner').src='about:blank'}render();queueProgress()}});
$('scan').onclick=()=>scan('materiel');$('case').onclick=()=>scan('mallette');$('finish').onclick=finish;
$('names').onclick=e=>{const next=e.target.dataset.person;if(NAMES.includes(next)){PhoneAlerts.enable(false);select(next)}};
$('sound').onclick=async()=>{const d=await PhoneAlerts.enable(true);$('soundNote').textContent=d.message};
try{const h=new URLSearchParams(location.hash.slice(1));registry=validateRegistry(h.has('stations')?{url:h.get('relay'),stations:JSON.parse(h.get('stations'))}:read('inst-v7-registry-mobile'));history.replaceState(null,'',location.pathname+location.search);person=read('inst-v7-person-mobile')||'QUENTIN'}catch(e){$('status').textContent=e.message}
select(NAMES.includes(person)?person:'QUENTIN');setInterval(poll,5000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)poll()});
