'use strict';
(()=>{
const C=window.MOBILE_CONFIG,K=window.MobileCore,$=id=>document.getElementById(id),S={auth:null,account:null,api:null,flow:null,profile:localStorage.getItem('mobile-profile')||'',incoming:null,task:null,codes:[],mallette:'',details:{},busy:false,polling:false,nonce:null};
const tell=(msg,error=false)=>{$('message').hidden=false;$('message').textContent=msg;$('message').classList.toggle('error',error)};
const guard=fn=>async(...args)=>{try{await fn(...args)}catch(e){tell(e.message||'Action impossible.',true)}};
const key=()=>`mobile-draft-${S.account?.homeAccountId}-${S.profile}`;
function save(){if(S.task)sessionStorage.setItem(key(),JSON.stringify({task:S.task,codes:S.codes,mallette:S.mallette}));else sessionStorage.removeItem(key())}
function facts(id,row){const box=$(id);box.replaceChildren();for(const [label,field]of [['VIN','VIN'],['Équipement','NumeroEquipement'],['Moteur','Moteur'],['Contrat','Contrat'],['Flotte','Flotte']]){const div=document.createElement('div'),small=document.createElement('small'),strong=document.createElement('strong');small.textContent=label;strong.textContent=row.fields[field]||'—';div.append(small,strong);box.append(div)}}
function render(){for(const b of document.querySelectorAll('[data-profile]')){const yes=b.dataset.profile===S.profile;b.classList.toggle('active',yes);b.setAttribute('aria-pressed',String(yes));b.disabled=S.busy||!!S.task||!!S.incoming}$('waiting').hidden=!!S.task||!!S.incoming;$('received').hidden=!S.incoming;$('task').hidden=!S.task;$('waitingTitle').textContent=S.profile?'Téléphone de '+K.profiles[S.profile]:'Choisissez votre prénom';$('waitingText').textContent=S.profile?'En attente d’une fiche PC. Gardez cette page ouverte.':'La fiche reçue apparaîtra ici.';if(S.incoming){$('receivedCM').textContent=S.incoming.fields.ContreMarque;facts('receivedFacts',S.incoming)}
 if(S.task){$('taskCM').textContent=S.task.fields.ContreMarque;facts('taskFacts',S.task);$('mallette').textContent=S.mallette||'Aucune mallette scannée';$('count').textContent=S.codes.length;const box=$('materials');box.replaceChildren();for(const code of S.codes){const card=document.createElement('div'),info=document.createElement('div'),name=document.createElement('strong'),detail=document.createElement('small'),remove=document.createElement('button');card.className='material';const d=S.details[code];name.textContent=d?.stock?.fields.TypeMateriel||code;detail.textContent=d?.error?'⚠ '+d.error:d?.stock?[d.stock.fields.Modele,d.stock.fields.Numero,code].filter(Boolean).join(' · '):'Vérification à la validation';remove.textContent='×';remove.setAttribute('aria-label','Retirer '+code);remove.disabled=S.busy;remove.onclick=()=>{S.codes=S.codes.filter(c=>c!==code);delete S.details[code];save();render()};info.append(name,detail);card.append(info,remove);box.append(card)}}
 for(const id of ['accept','refuse','refresh','scanMallette','scanMaterials','resume','validate'])$(id).disabled=S.busy||(id==='validate'&&!S.codes.length);$('validate').textContent=S.busy?'Enregistrement…':'Valider et transmettre au PC'}
async function token(){try{return(await S.auth.acquireTokenSilent({scopes:C.scopes,account:S.account})).accessToken}catch(e){if(e instanceof msal.InteractionRequiredAuthError)throw Error('Connexion expirée. Utilisez le bouton Connexion Microsoft en haut pour reprendre.');throw e}}
async function poll(){if(!S.api||!S.profile||S.task||S.incoming||S.busy||S.polling||document.hidden)return;S.polling=true;try{const rows=await S.api.rows('planning','ScanSession',S.profile);S.incoming=rows.filter(r=>K.isRequest(r,S.profile)).sort((a,b)=>Date.parse(a.fields.ScanDate)-Date.parse(b.fields.ScanDate))[0]||null;render()}finally{S.polling=false}}
async function restore(){try{const d=JSON.parse(sessionStorage.getItem(key())||'null');if(d?.task&&Array.isArray(d.codes)&&d.codes.every(K.validCode)){S.task=K.own(await S.api.item('planning',d.task.id),d.task,S.profile);S.codes=[...new Set(d.codes.map(K.normalize))];S.mallette=K.validCode(d.mallette)?d.mallette:''}}catch(e){S.task=null;sessionStorage.removeItem(key());tell('Ancienne fiche clôturée ou remplacée : attente d’une nouvelle demande.',true)}render()}
async function accept(){if(S.busy||!S.incoming)return;S.busy=true;render();try{const row=await S.api.item('planning',S.incoming.id);if(!K.isRequest(row,S.profile)||row.fields.ScanJeton!==S.incoming.fields.ScanJeton){S.incoming=null;throw Error('La demande n’est plus disponible.');}S.task=await S.api.patch('planning',row,{ScanStatut:'En cours'});S.incoming=null;S.codes=[];S.mallette='';S.details={};save();S.busy=false;render();openScan('materiel')}finally{S.busy=false;render()}}
function openScan(mode){if(!S.task||S.busy)return;S.nonce=crypto.randomUUID();const u=new URL('scan-mobile.html',location.href);u.search=new URLSearchParams({mode,cm:S.task.fields.ContreMarque,mallette:S.mallette,items:S.codes.join('|'),scanSessionId:S.nonce,scanRequest:S.task.id,returnMode:'web',nonce:S.nonce}).toString();$('scanFrame').src=u.href;$('scanner').hidden=false}
async function receiveScan(e){if(e.origin!==location.origin||e.source!==$('scanFrame').contentWindow||e.data?.type!=='instrumentation-mobile-batch'||e.data.nonce!==S.nonce||!S.task||String(e.data.request)!==S.task.id||e.data.cm!==S.task.fields.ContreMarque)return;const d=e.data;if(!Array.isArray(d.items)||d.items.length>1000||!d.items.every(K.validCode)||d.mallette&&!K.validCode(d.mallette))throw Error('Résultat du scanner invalide.');await S.flow.fresh(S.task);S.codes=[...new Set(d.items.map(K.normalize))];S.mallette=K.normalize(d.mallette);save();S.nonce=null;$('scanner').hidden=true;$('scanFrame').src='about:blank';render();for(const code of S.codes){try{S.details[code]=await S.flow.inspect(code,S.task)}catch(e){S.details[code]={error:e.message}}}render();tell('Liste récupérée. Vérifiez les matériels puis validez.')}
async function validate(){if(S.busy||!S.task)return;if(!confirm('Enregistrer '+S.codes.length+' matériel(s) sur '+S.task.fields.ContreMarque+' ?'))return;S.busy=true;render();try{await S.flow.validate(S.task,S.codes,S.mallette);S.task=null;save();S.codes=[];S.mallette='';S.details={};tell('Montage enregistré. La fiche du PC va s’actualiser.')}catch(e){tell('Enregistrement incomplet : '+e.message+' La liste est conservée. Vérifiez la fiche avant de réessayer.',true)}finally{S.busy=false;render()}}
async function boot(){if(!C.clientId){$('setup').hidden=false;$('login').disabled=true;return}if(!window.msal)throw Error('La connexion Microsoft n’a pas pu être chargée. Vérifiez le réseau.');const uri=new URL('mobile.html',location.href);uri.search='';uri.hash='';S.auth=new msal.PublicClientApplication({auth:{clientId:C.clientId,authority:'https://login.microsoftonline.com/'+C.tenantId,redirectUri:uri.href},cache:{cacheLocation:'sessionStorage'}});await S.auth.initialize();const response=await S.auth.handleRedirectPromise();S.account=response?.account||S.auth.getAllAccounts()[0];if(!S.account)return;S.auth.setActiveAccount(S.account);$('account').textContent=S.account.name||S.account.username;$('login').textContent='Renouveler la connexion Microsoft';$('auth').querySelector('h2').textContent='Compte connecté';$('auth').querySelector('p').hidden=true;S.api=K.createApi(C,token);await S.api.init();S.flow=K.createWorkflow(S.api,()=>S.account.name||S.account.username,()=>S.profile);if(!K.profiles[S.profile])S.profile='';$('profileCard').hidden=false;await restore();await poll();setInterval(guard(poll),5000)}
$('login').onclick=guard(async()=>{if(S.auth)await S.auth.loginRedirect({scopes:C.scopes})});for(const b of document.querySelectorAll('[data-profile]'))b.onclick=guard(async()=>{if(S.task||S.busy)return;S.profile=b.dataset.profile;localStorage.setItem('mobile-profile',S.profile);await restore();await poll();render()});$('refresh').onclick=guard(poll);$('accept').onclick=guard(accept);$('refuse').onclick=guard(async()=>{if(!S.incoming||S.busy)return;S.busy=true;render();try{const row=await S.api.item('planning',S.incoming.id);if(!K.isRequest(row,S.profile)||row.fields.ScanJeton!==S.incoming.fields.ScanJeton){S.incoming=null;throw Error('Cette demande a changé.');}await S.api.patch('planning',row,{ScanStatut:'Refusé'});S.incoming=null;tell('Demande refusée.')}finally{S.busy=false;render()}});$('scanMallette').onclick=()=>openScan('mallette');$('scanMaterials').onclick=()=>openScan('materiel');$('resume').onclick=()=>openScan('materiel');$('validate').onclick=guard(validate);$('backFromScan').onclick=()=>{if(!confirm('Revenir à la fiche ? Les scans non transmis de cette ouverture seront abandonnés.'))return;S.nonce=null;$('scanner').hidden=true;$('scanFrame').src='about:blank';render()};window.addEventListener('message',guard(receiveScan));document.addEventListener('visibilitychange',guard(poll));window.addEventListener('pagehide',save);guard(boot)();
})();
