'use strict';
const $=id=>document.getElementById(id),L=GlobalLogic,api=SharePointAPI,profiles=MobileCore.profiles;
let connected=false,loading=false,mutating=false,weekStart=L.monday(L.today()),rows=[],selected=null,detailVersion=0,assignments=new Map(),mode='manual',codes=[],editRow=null,savedRow=null,validation=null,relayLoading=false;
let rooms={};try{rooms=JSON.parse(sessionStorage.getItem('inst-global-rooms-v4')||'{}')}catch{}
const status=text=>$('status').textContent=text;
function element(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e}
function saveRooms(){sessionStorage.setItem('inst-global-rooms-v4',JSON.stringify(rooms))}
function busy(value){mutating=value;['saveVehicle','new','confirmValidation'].forEach(id=>$(id).disabled=value||id==='new'&&!connected)}
function name(){return $('fullName').value.trim()||profiles[$('operator').value]}
function clock(){ $('clock').textContent=new Intl.DateTimeFormat('fr-FR',{timeZone:'Europe/Paris',weekday:'short',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date());$('who').textContent=name() }
clock();setInterval(clock,1000);
$('operator').onchange=()=>{$('fullName').value=$('operator').value==='QUENTIN'?'Quentin Barthelemy':profiles[$('operator').value];clock()};
$('connect').onclick=async()=>{if(loading)return;$('connect').disabled=true;status('Vérification des listes SharePoint…');try{await api.init();connected=true;$('new').disabled=false;$('setup').querySelector('h2').textContent='Atelier connecté';await refresh();status('SharePoint connecté. Les modifications utilisent tes droits habituels.')}catch(e){status(e.message)}finally{$('connect').disabled=false}};
function renderWeeks(){const current=L.iso(weekStart);$('week').value=current.year+'-W'+String(current.week).padStart(2,'0');$('weeks').replaceChildren();for(let i=-2;i<=2;i++){const d=L.shift(weekStart,i*7),info=L.iso(d),b=element('button','S'+info.week,i===0?'active':'');b.title='Semaine '+info.week+' · '+info.year;b.onclick=()=>changeWeek(d);$('weeks').append(b)}}
function changeWeek(d){weekStart=d;renderWeeks();if(connected)refresh()}
$('prev').onclick=()=>changeWeek(L.shift(weekStart,-7));$('next').onclick=()=>changeWeek(L.shift(weekStart,7));$('week').onchange=()=>{if($('week').value)changeWeek(L.fromWeek($('week').value))};renderWeeks();
async function materials(cm,force=false){if(force||!assignments.has(cm)){const a=(await api.rows('assignments','ContreMarque',cm)).filter(x=>x.fields.Actif===true);assignments.set(cm,a)}return assignments.get(cm)||[]}
function rowNode(row){const f=row.fields,a=assignments.get(f.ContreMarque)||[],tr=element('tr',undefined,'vehicle '+L.color(f)+(selected===row.id?' selected':''));tr.dataset.id=row.id;tr.tabIndex=0;tr.setAttribute('aria-selected',String(selected===row.id));tr.setAttribute('aria-label','Ouvrir le véhicule '+f.ContreMarque);tr.onclick=()=>select(row.id);tr.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select(row.id)}};
 const date=f.DateMontage?L.date(f.DateMontage):'';const day=date?new Intl.DateTimeFormat('fr-FR',{weekday:'short',day:'2-digit',month:'2-digit',timeZone:'UTC'}).format(new Date(date+'T12:00:00Z')):'';
 const values=[day,f.Operateur,f.ContreMarque,f.NumeroEquipement,f.VIN,f.Moteur,f.Contrat,f.Flotte,L.mallette(a),f.Commentaire];values.forEach((v,i)=>{const td=element('td',v||'—',i===2?'cm':'');td.title=v||'';tr.append(td)});
 const td=element('td',undefined,'summary');td.append(element('small',a.length+' matériel(s)'+(a.length?' · '+a.map(x=>x.fields.TypeMateriel||x.fields.CodeMateriel).join(', '):'')));for(const k of L.keys){const ok=L.valid(f[k]),span=element('span',(ok?'✓ ':'× ')+k,'pill '+(ok?'ok':'no'));span.title=L.labels[k]+(ok?' : '+f[k]+'':' : à valider');td.append(span)}tr.append(td);return tr}
function renderRows(){const body=$('rows'),previous=new Map([...body.children].map(e=>[e.dataset.id,e]));for(const row of rows){const a=assignments.get(row.fields.ContreMarque)||[],signature=JSON.stringify([row.fields,a.map(x=>x.fields),selected===row.id]);let tr=previous.get(row.id);if(!tr||tr.dataset.signature!==signature){const next=rowNode(row);next.dataset.signature=signature;if(tr)tr.replaceWith(next);tr=next}previous.delete(row.id);const pos=rows.indexOf(row);if(body.children[pos]!==tr)body.insertBefore(tr,body.children[pos]||null)}previous.forEach(e=>e.remove());$('empty').hidden=!!rows.length;$('empty').textContent='Aucun véhicule prévu cette semaine.';$('count').textContent=rows.length+' véhicule(s)';$('sync').textContent='Actualisé à '+new Date().toLocaleTimeString('fr-FR',{timeZone:'Europe/Paris'});}
async function refresh(){if(!connected||loading||mutating)return;loading=true;const requested=weekStart;try{const next=await api.week(requested,L.shift(requested,7));if(requested!==weekStart)return;await Promise.all([...new Set(next.map(r=>r.fields.ContreMarque).filter(Boolean))].map(cm=>materials(cm,true)));if(requested!==weekStart)return;rows=next.sort((a,b)=>String(a.fields.DateMontage).localeCompare(String(b.fields.DateMontage))||Number(a.fields.OrdreJour||0)-Number(b.fields.OrdreJour||0)||a.id.localeCompare(b.id,undefined,{numeric:true}));renderRows();if(selected){const row=rows.find(r=>r.id===selected);if(row)renderDetail(row);else{$('detail').hidden=true;selected=null}}}catch(e){status('Actualisation impossible : '+e.message+' Les informations affichées sont conservées.')}finally{loading=false;if(requested!==weekStart)refresh()}}
function select(id){selected=id;renderRows();const row=rows.find(r=>r.id===id);if(row)renderDetail(row);$('detail').hidden=false}
$('closeDetail').onclick=()=>{selected=null;$('detail').hidden=true;renderRows()};
function renderDetail(row){const f=row.fields,a=assignments.get(f.ContreMarque)||[],sig=JSON.stringify([row.id,f,a.map(x=>x.fields)]);if($('detailContent').dataset.signature===sig)return;$('detailContent').dataset.signature=sig;const c=$('detailContent');c.replaceChildren(element('p','FICHE VÉHICULE','subtitle'),element('h2',f.ContreMarque),element('p',f.StatutMontage||'Planifié','subtitle'));const facts=element('div',undefined,'facts');for(const [label,v]of [['Équipement',f.NumeroEquipement],['VIN',f.VIN],['Moteur',f.Moteur],['Contrat',f.Contrat],['Flotte',f.Flotte],['Mallette',L.mallette(a)]]){const div=element('div');div.append(element('span',label),element('strong',v||'—'));facts.append(div)}c.append(facts);if(f.Commentaire)c.append(element('p',f.Commentaire));c.append(element('h3','Validations'));for(const k of L.keys){const ok=L.valid(f[k]),div=element('div',undefined,'validation'+(ok?' done':'')),text=element('div',undefined,'text');div.append(element('span',ok?'✓':'×','symbol'));text.append(element('strong',L.labels[k]),element('small',ok?f[k]:'À valider'));div.append(text);if(!ok){const b=element('button','Valider','secondary');b.onclick=()=>openValidation(row,k);div.append(b)}c.append(div)}c.append(element('h3','Matériels · '+a.length));for(const item of a){const m=item.fields,card=element('div',undefined,'material-card');card.append(element('strong',m.TypeMateriel||'Matériel'),element('div',m.CodeMateriel),element('small',[m.Modele,m.Numero&&'N° '+m.Numero].filter(Boolean).join(' · ')));c.append(card)}if(!a.length)c.append(element('p','Aucun matériel affecté.','subtitle'));const act=element('div',undefined,'detail-actions'),edit=element('button','Modifier la fiche','secondary');edit.onclick=()=>openForm(row);act.append(edit);const target=element('select');for(const [v,label]of Object.entries(profiles)){const o=element('option',label);o.value=v;target.append(o)}target.value=f.ScanSession||$('operator').value;const send=element('button','Envoyer un scan au téléphone');send.onclick=async()=>{if(mutating)return;busy(true);try{await dispatch(row,target.value);status('Demande envoyée à '+profiles[target.value]+' pour '+f.ContreMarque)}catch(e){status(e.message)}finally{busy(false);await refresh()}};act.append(target,send);if(f.ScanStatut)c.append(element('p','Scan '+(f.ScanSession||'')+' : '+f.ScanStatut,'subtitle'));c.append(act)}
function openValidation(row,key){validation={id:row.id,key};$('validationTitle').textContent=L.labels[key];$('validationVehicle').textContent='Véhicule '+row.fields.ContreMarque;$('initials').value=L.initials(name());$('validationStatus').textContent='';$('validationDialog').showModal()}
$('validationForm').onsubmit=async e=>{e.preventDefault();if(mutating)return;busy(true);try{const row=await api.item('planning',validation.id);if(L.valid(row.fields[validation.key]))throw Error('Cette étape a déjà été validée.');const value=$('initials').value.trim().toUpperCase()+' · '+new Date().toLocaleString('fr-FR',{timeZone:'Europe/Paris'});await api.patch('planning',row,{[validation.key]:value});$('validationDialog').close();status('Validation enregistrée.')}catch(e){$('validationStatus').textContent=e.message}finally{busy(false);await refresh()}};
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>{if(!mutating)$(b.dataset.close).close()});
function setMode(v){mode=v;$('manualFields').hidden=v!=='manual';$('scanFields').hidden=v!=='scan';$('manualMode').classList.toggle('active',v==='manual');$('scanMode').classList.toggle('active',v==='scan');$('saveVehicle').textContent=v==='scan'?'Enregistrer et envoyer le scan':editRow?'Enregistrer la fiche':'Créer le véhicule'}
$('manualMode').onclick=()=>setMode('manual');$('scanMode').onclick=()=>setMode('scan');
function openForm(row=null){editRow=row;savedRow=null;codes=[];$('createForm').reset();const f=row?.fields||{};$('date').value=f.DateMontage?L.date(f.DateMontage):L.today();$('preparer').value=f.ScanSession||$('operator').value;$('target').value=$('operator').value;for(const [id,key]of Object.entries({cm:'ContreMarque',equip:'NumeroEquipement',vin:'VIN',engine:'Moteur',contract:'Contrat',fleet:'Flotte',remark:'Commentaire'}))$(id).value=f[key]||'';$('cm').disabled=!!row;$('date').disabled=!!row;$('manualCase').value=row?L.mallette(assignments.get(f.ContreMarque)||[]):'';$('formTitle').textContent=row?'Modifier '+f.ContreMarque:'Créer un véhicule';$('formStatus').textContent='';renderCodes();setMode('manual');$('createDialog').showModal()}
$('new').onclick=()=>openForm();function renderCodes(){$('materialList').replaceChildren();codes.forEach(code=>{const li=element('li'),b=element('button','×','icon');b.type='button';b.setAttribute('aria-label','Retirer '+code);b.onclick=()=>{codes=codes.filter(x=>x!==code);renderCodes()};li.append(element('span',code),b);$('materialList').append(li)})}
$('addMaterial').onclick=()=>{const code=MobileCore.normalize($('materialCode').value);if(!MobileCore.validCode(code)){$('formStatus').textContent='Code matériel invalide.';return}if(codes.length>=200){$('formStatus').textContent='Maximum 200 matériels.';return}if(!codes.includes(code))codes.push(code);$('materialCode').value='';renderCodes()};$('materialCode').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();$('addMaterial').click()}};
async function unique(list,field,value){const r=await api.rows(list,field,value);if(r.length>1)throw Error('Plusieurs fiches correspondent à '+value+'. Corrige le doublon dans SharePoint.');return r[0]||null}
async function persistVehicle(){const cm=MobileCore.normalize($('cm').value),date=$('date').value;if(!MobileCore.validCode(cm)||cm.length>80)throw Error('Contre marque invalide (80 caractères maximum).');const day=new Date(date+'T12:00:00Z');if(!Number.isFinite(+day))throw Error('Jour de montage invalide.');const info=L.iso(date),who=profiles[$('preparer').value],metadata={ContreMarque:cm,NumeroEquipement:$('equip').value.trim(),VIN:$('vin').value.trim().toUpperCase(),Moteur:$('engine').value.trim(),Contrat:$('contract').value.trim(),Flotte:$('fleet').value.trim()},now=new Date().toISOString();if(!editRow&&!savedRow&&await unique('planning','PlanningID',date.replaceAll('-','')+'-'+cm))throw Error('Ce véhicule est déjà prévu ce jour. Ouvre sa ligne pour modifier la fiche.');let vehicle=await unique('vehicles','ContreMarque',cm);if(vehicle)vehicle=await api.patch('vehicles',vehicle,{...metadata,DerniereModificationInstrumentation:now});else vehicle=await api.create('vehicles',{Title:cm,...metadata,Actif:true,StatutInstrumentation:'Planifié',DerniereModificationInstrumentation:now});
 const pid=date.replaceAll('-','')+'-'+cm;let plan=savedRow?await api.item('planning',savedRow.id):editRow?editRow:await unique('planning','PlanningID',pid);if(plan&&!editRow&&!savedRow)throw Error('Ce véhicule est déjà prévu ce jour. Ouvre sa ligne pour modifier la fiche ou envoyer un scan.');const fields={...metadata,Commentaire:$('remark').value.trim(),Operateur:who};if(plan)plan=await api.patch('planning',plan,fields);else plan=await api.create('planning',{Title:cm,PlanningID:pid,...fields,DateMontage:date+'T12:00:00Z',Semaine:info.week,Annee:info.year,OrdreJour:(day.getUTCDay()+6)%7+1,...(day.getUTCDay()>0&&day.getUTCDay()<6?{JourSemaine:['Dimanche','Lundi','Mardi','Mercredi','Jeudi','Vendredi','Samedi'][day.getUTCDay()]}:{}),StatutMontage:'Planifié',DateCreationPlanning:now,NB_MAT:0,NB_MTG:0});savedRow=plan;return plan}
$('createForm').onsubmit=async e=>{e.preventDefault();if(mutating)return;busy(true);$('formStatus').textContent='Enregistrement…';try{if(mode==='scan'&&!rooms[$('target').value])throw Error('Crée d’abord la liaison pour '+profiles[$('target').value]+' dans « Téléphones ».');let plan=await persistVehicle();if(mode==='scan'){await dispatch(plan,$('target').value)}else if(codes.length){if(plan.fields.ScanStatut==='Demandé')throw Error('Une demande téléphone attend déjà sur cette fiche. Termine-la avant la saisie manuelle.');const profile=$('preparer').value;if(!(plan.fields.ScanStatut==='En cours'&&plan.fields.ScanSession===profile&&plan.fields.ScanJeton))plan=await api.patch('planning',await api.item('planning',plan.id),{ScanSession:profile,ScanStatut:'En cours',ScanJeton:crypto.randomUUID(),ScanDate:new Date().toISOString()});savedRow=plan;await MobileCore.createWorkflow(api,()=>profiles[profile],()=>profile).validate(plan,codes,MobileCore.normalize($('manualCase').value))}else if($('manualCase').value.trim())throw Error('La fiche est créée. Pour affecter une mallette, ajoute au moins un matériel ou utilise le scan.');weekStart=L.monday($('date').value);renderWeeks();selected=plan.id;$('createDialog').close();status(mode==='scan'?'Fiche enregistrée. Demande envoyée au téléphone.':'Fiche enregistrée dans SharePoint.')}catch(e){$('formStatus').textContent=e.message+(savedRow?' La fiche est conservée. Corrige puis réessaie.':'')}finally{busy(false);await refresh()}};
function relayBase(value){const u=new URL(value);if(u.protocol!=='https:'||!u.hostname.endsWith('.workers.dev')||u.username||u.password)throw Error('Adresse HTTPS workers.dev invalide.');return u.origin}
async function call(url,options){const r=await fetch(url,{...options,cache:'no-store',signal:AbortSignal.timeout(20000)});let b;try{b=await r.json()}catch{throw Error('Réponse du relais invalide.')}if(!r.ok){const e=Error(b.error||'Erreur du relais '+r.status);e.status=r.status;throw e}return b}
function relay(room,path,body){return call(room.url+'/rooms/'+room.id+'/'+path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+room.token,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})})}
function showLink(room){const u=new URL('../scan-relais/liaison.html',location.href);u.search='?v=4';u.hash=new URLSearchParams({relay:room.url,id:room.id,token:room.mobileToken,person:room.person});$('phoneLink').hidden=false;$('phoneLink').value=u.href;navigator.clipboard?.writeText(u.href).then(()=>$('relayStatus').textContent='Lien privé copié. Ouvre-le sur le téléphone de '+profiles[room.person]+'.').catch(()=>$('relayStatus').textContent='Copie le lien affiché et ouvre-le sur le téléphone.');}
function renderPhones(){const parent=$('phones');parent.replaceChildren();for(const [person,label]of Object.entries(profiles)){const room=rooms[person],div=element('div');div.append(element('strong',label));const b=element('button',room?'Copier le lien':'Créer la liaison');b.onclick=async()=>{if(relayLoading)return;if(room){showLink(room);return}b.disabled=true;try{const url=relayBase($('relayUrl').value.trim()),key=$('relayKey').value;if(key.length<32)throw Error('Renseigne le code privé ACCESS_KEY.');const r=await call(url+'/rooms',{method:'POST',headers:{'Content-Type':'application/json','X-Access-Key':key},body:JSON.stringify({person})});rooms[person]={url,id:r.id,token:r.pcToken,mobileToken:r.mobileToken,person,expires:r.expires,job:null};saveRooms();showLink(rooms[person]);renderPhones()}catch(e){$('relayStatus').textContent=e.message;b.disabled=false}};div.append(b);if(room){const close=element('button','Fermer','secondary');close.onclick=async()=>{if(room.job){$('relayStatus').textContent='Une demande est en cours. Termine son enregistrement avant de fermer.';return}if(!confirm('Fermer la liaison de '+label+' ? Son lien ne fonctionnera plus.'))return;try{await relay(room,'close',{});delete rooms[person];saveRooms();renderPhones()}catch(e){if(e.status===410){delete rooms[person];saveRooms();renderPhones()}else $('relayStatus').textContent=e.message}};div.append(close);if(room.error){const retry=element('button','Réessayer l’enregistrement','secondary');retry.onclick=()=>{room.error=null;saveRooms();pollRooms()};div.append(retry);if(room.beforeWrite){const revise=element('button','Corriger sur le téléphone','secondary');revise.onclick=async()=>{try{const r=await relay(room,'status');if(!r.result)throw Error('Aucun lot à corriger.');await relay(room,'revision',{id:r.result.id});room.error=null;room.beforeWrite=false;saveRooms();renderPhones();$('relayStatus').textContent='Le téléphone peut corriger son lot puis le renvoyer.'}catch(e){$('relayStatus').textContent=e.message}};div.append(revise)}}div.append(element('small',room.error||room.info||'Liaison créée · expire '+new Date(room.expires).toLocaleString('fr-FR')))}parent.append(div)}}
$('relayButton').onclick=()=>{renderPhones();$('relayDialog').showModal()};$('relayDialog').addEventListener('close',()=>{$('relayKey').value='';$('phoneLink').value='';$('phoneLink').hidden=true});
async function dispatch(plan,person){const room=rooms[person];if(!room)throw Error('Crée la liaison de '+profiles[person]+' dans « Téléphones ».');if(room.expires<Date.now())throw Error('Liaison expirée : ferme-la puis crée-en une nouvelle.');const remote=await relay(room,'status');if(remote.result)throw Error('Le précédent scan doit être enregistré avant le suivant.');if(remote.task&&(!room.job||room.job.id!==remote.task.id||room.job.planningId!==plan.id))throw Error('Ce téléphone a déjà une demande en cours.');if(!remote.task&&room.job?.created&&Date.now()-room.job.created>1800000)room.job=null;const current=await api.item('planning',plan.id);if(['Demandé','En cours'].includes(current.fields.ScanStatut)&&Date.now()-Date.parse(current.fields.ScanDate)<1800000&&(!room.job||current.fields.ScanJeton!==room.job.id))throw Error('Ce véhicule a déjà une demande de scan en cours.');room.job=room.job&&room.job.planningId===plan.id?room.job:{id:crypto.randomUUID(),cm:current.fields.ContreMarque,planningId:plan.id,created:Date.now()};saveRooms();await api.patch('planning',current,{ScanSession:person,ScanStatut:'Demandé',ScanJeton:room.job.id,ScanDate:new Date().toISOString()});await relay(room,'task',{id:room.job.id,cm:room.job.cm});room.error=null;room.info='Demande envoyée · '+room.job.cm;saveRooms();renderPhones()}
async function commitResult(room,result){if(result.person!==room.person)throw Error('Destinataire du résultat incohérent.');let plan=await unique('planning','ScanJeton',result.id);if(!plan||plan.fields.ContreMarque!==result.cm||plan.fields.ScanSession!==room.person)throw Error('Le scan ne correspond plus à la fiche SharePoint. Aucun nouveau matériel ne sera affecté.');if(plan.fields.ScanStatut==='Terminé'){await relay(room,'ack',{id:result.id});room.job=null;room.error=null;room.info='Enregistré · '+result.cm;saveRooms();return}if(!['Demandé','En cours'].includes(plan.fields.ScanStatut))throw Error('La demande SharePoint a changé.');const date=Date.parse(plan.fields.ScanDate);if(!Number.isFinite(date)||result.validatedAt<date-60000||result.validatedAt>date+1800000)throw Error('Le résultat ne correspond pas à la période de la demande.');if(!result.items?.length)throw Error('Aucun matériel scanné. La mallette seule ne peut pas terminer un montage.');if(plan.fields.ScanStatut==='Demandé')plan=await api.patch('planning',plan,{ScanStatut:'En cours'});await MobileCore.createWorkflow(api,()=>profiles[room.person],()=>room.person).validate(plan,result.items,result.mallette);await relay(room,'ack',{id:result.id});room.job=null;room.error=null;room.info='Enregistré · '+result.cm;saveRooms();status('✓ Scan de '+profiles[room.person]+' enregistré sur '+result.cm+'.');}
async function pollRooms(){if(relayLoading||mutating||!connected||document.hidden)return;relayLoading=true;let changed=false;try{for(const room of Object.values(rooms)){try{const r=await relay(room,'status');room.info=r.mobileOnline?'Téléphone connecté':'Téléphone absent ou en arrière-plan';if(r.result&&!room.error){busy(true);try{await commitResult(room,r.result);changed=true}catch(e){room.error='Scan conservé : '+e.message;room.beforeWrite=!!e.beforeWrite;try{await relay(room,'feedback',{id:r.result.id,message:room.error.slice(0,500)})}catch{}status(room.person+' · '+room.error+' Ouvre « Téléphones » pour réessayer ou corriger le lot.')}finally{busy(false)}}else if(!r.result&&room.job&&r.task?.id!==room.job.id){room.error='Demande expirée ou non envoyée. Rouvre la fiche et réessaie.';}saveRooms()}catch(e){room.error=e.message}}if($('relayDialog').open)renderPhones()}finally{relayLoading=false;if(changed)await refresh()}}
setInterval(()=>{if(!document.hidden){refresh();pollRooms()}},5000);document.addEventListener('visibilitychange',()=>{if(!document.hidden){refresh();pollRooms()}});
